services:
  bedrock-playit:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PLAYIT_SECRET=${PLAYIT_SECRET_KEY}
    ports:
      - "19132:19132/udp"
    restart: unless-stopped
